basket/urls.py
from django.urls import path
from .views import basket_summary, basket_add, basket_delete, basket_update

app_name = 'basket'

urlpatterns = [
    path('', basket_summary, name='basket_summary'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('book/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:slug_category>/', views.category_list, name='category_list')
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(max_length=255, unique=True, verbose_name='Category name', help_text='Required and uniq')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='Category safe url')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse(viewname='shop:category_list', args=[self.slug])

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category


def all_products(request):
    products = Product.product.all()
    return render(request, template_name='shop/home.html', context={'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, template_name='shop/detail.html', context={'product': product})


def category_list(request, slug_category):
    category = get_object_or_404(Category, slug=slug_category)
    products = Product.objects.filter(category=category, is_active=True)
    return render(request,
                  template_name='shop/category_list.html',
                  context={'category': category, 'products': products})

templates/shop/category_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Books{% endif %}
{% endblock %}
{% block content %}


<main>
<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div><b>Popular</b> products purchased</div>
  </div>
  <hr />
</div>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">Popular</h1></div>
        {% if not products %}
          <div class="col-12">There are currently no products active <a href="{% url 'shop:all_products' %}">Home</a></div>
        {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            {% for product in products %}
              <div class="col">
                <div class="card border-0">
                  <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                  <div class="card-body px-0">
                    <p class="card-text">
                      <a class="text-dark text-decoration-none"
                        href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">£{{product.price}}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/shop/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}


<main class="pt-2">
  <div class="container" style="max-width: 1000px">

    <div class="row g-3">

        <div class="col-12 d-flex justify-content-between">

        </div>

        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grid gap-2">

            <div class="d-flex d-flex-inline justify-content-between">
            <div><span class="h3">£{{ product.price }}</span><p class="text-muted">includes tax</p></div>
                   <div class="">
                                <label for="select">Qty</label>
                                <select id="select" class="h6" style="width:50px;height:40px;">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                    </div>
            </div>
            <hr>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to basket</button>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Add to Favorites</button>
            </div>
        </div>

        <div class="col-md-7 col-lg-7 p-0">



            <div class="card mb-3 border-0">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-body p-1">
                        <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                        <div class="bg-light"><img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}"> </div>
                    </div>

                </div>
            </div>
            </div>



        </div>

    </div>
  </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}

templates/shop/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}BookStore{% endblock %}
{% block content %}
<main>
  <div class="container">
    <div class="container">
      <div class="row">
        <div class="album py-5">
          <div class="pb-3">
            <h1 class="h3">Popular</h1>
          </div>
          {% if not products %}
              <div class="col-12">There are currently no products active</div>
          {% else %}
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
              {% for product in products %}
                <div class="col">
                  <div class="card border-0">
                    <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                    <div class="card-body px-0">
                      <p class="card-text">
                        <a class="text-dark text-decoration-none"
                          href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}...</a>
                      </p>
                      <div class="fw-bold">£{{product.price}}</div>
                    </div>
                  </div>
                </div>
              {% endfor %}
              </div>
          {% endif %}


        </div>
      </div>
    </div>
</main>
{% endblock %}